/* Historical text reader. No invented temperatures, timings or safety validation. */
(()=>{
'use strict';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
window.mountArchiveReader=(root,source,key)=>{
 const lines=source.body.split('\n');let section='',ingredients=[],steps=[];
 for(const line of lines){if(/^##\s/.test(line)){section=line.replace(/^##\s*/,'').toLowerCase();continue}if(/ingredients/.test(section)&&/^[-*]\s/.test(line))ingredients.push(line.replace(/^[-*]\s*/,''));if(/directions|method|instructions/.test(section)){const numbered=line.match(/^\s*\d+[.)]\s+(.*)/);if(numbered)steps.push(numbered[1]);else if(line.trim()&&steps.length)steps[steps.length-1]+=' '+line.trim()}}
 if(!steps.length){root.innerHTML='<p>This source has no reliably separable numbered steps. Read the original text below; no steps or timings have been invented.</p>';return}
 const storageKey='little-miss-archive-reader:'+key;let state={index:0,done:[],ingredients:[],notes:''},available=true;
 try{const stored=JSON.parse(localStorage.getItem(storageKey)||'null');if(stored&&Array.isArray(stored.done)&&Array.isArray(stored.ingredients)){state={...state,...stored};state.index=Math.max(0,Math.min(steps.length-1,Number(state.index)||0))}}catch(e){available=false}
 const save=()=>{try{localStorage.setItem(storageKey,JSON.stringify(state))}catch(e){available=false}const status=root.querySelector('.reader-save-status');if(status)status.textContent=available?'Saved on this browser.':'Browser storage is unavailable; progress will last only while this record stays open.'};
 root.innerHTML=`<section class="archive-reader"><h3>Read it step by step</h3><p class="source-note">A guided reader for historical source text. This does not modernise or validate the method. Timing is only available where the original text states it.</p><details><summary>Ingredient checklist (${ingredients.length})</summary><p class="source-note">Amounts below are exactly as supplied in the archive. An omitted amount remains unspecified.</p><ul class="ingredient-list">${ingredients.map((s,i)=>`<li><label><input type="checkbox" data-reader-ingredient="${i}" ${state.ingredients.includes(i)?'checked':''}><span>${esc(s)}</span></label></li>`).join('')}</ul></details><p class="reader-count" role="status"></p><progress class="cook-progress" max="${steps.length}" value="0" aria-label="Historical reading progress"></progress><div class="reader-step" aria-live="polite"></div><label class="cook-check"><input type="checkbox" class="reader-done"> Mark this step as read</label><div class="cook-nav"><button class="kbtn reader-prev">← Previous</button><button class="kbtn primary reader-next">Next →</button></div><label class="reader-notes-label">Questions and adaptation notes<textarea class="personal-notes" placeholder="What needs checking or adapting for a modern kitchen?">${esc(state.notes)}</textarea></label><p class="reader-save-status source-note" role="status"></p></section>`;
 const render=()=>{root.querySelector('.reader-count').textContent=`Step ${state.index+1} of ${steps.length} · ${state.done.length} marked as read`;root.querySelector('progress').value=state.done.length;root.querySelector('.reader-step').innerHTML=`<h4>Original step ${state.index+1}</h4><p>${esc(steps[state.index])}</p>`;root.querySelector('.reader-done').checked=state.done.includes(state.index);root.querySelector('.reader-prev').disabled=state.index===0;root.querySelector('.reader-next').disabled=state.index===steps.length-1;save()};
 root.querySelector('.reader-prev').onclick=()=>{state.index--;render()};root.querySelector('.reader-next').onclick=()=>{state.index++;render()};root.querySelector('.reader-done').onchange=e=>{state.done=state.done.filter(i=>i!==state.index);if(e.target.checked)state.done.push(state.index);render()};root.querySelectorAll('[data-reader-ingredient]').forEach(c=>c.onchange=()=>{const i=+c.dataset.readerIngredient;state.ingredients=state.ingredients.filter(n=>n!==i);if(c.checked)state.ingredients.push(i);save()});root.querySelector('textarea').oninput=e=>{state.notes=e.target.value;save()};render();
};
})();
