(() => {
'use strict';
const recipes=window.KITCHEN_RECIPES, lessons=window.KITCHEN_LESSONS;
const $=(q,root=document)=>root.querySelector(q), $$=(q,root=document)=>[...root.querySelectorAll(q)];
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let state={saved:[],checked:{},progress:{},notes:''},storageOK=true;
try{const v=JSON.parse(localStorage.getItem('little-miss-kitchen-v2')||'null');if(v&&typeof v==='object')state={...state,...v};if(!Array.isArray(state.saved))state.saved=[];}catch(e){storageOK=false;}
function persist(){try{localStorage.setItem('little-miss-kitchen-v2',JSON.stringify(state));}catch(e){storageOK=false;toast('Browser storage is unavailable; changes will last for this visit only.')}}
let toastTimeout;const toastEl=document.createElement('div');toastEl.className='toast';toastEl.setAttribute('role','status');document.body.append(toastEl);
function toast(s){toastEl.textContent=s;clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>toastEl.textContent='',3500)}
function go(id,{scroll=true}={}){if(!document.getElementById(id))return;$$('.page').forEach(p=>p.classList.toggle('active',p.id===id));$$('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.page===id));$$('.hero-more[open]').forEach(d=>d.open=false);$('#empty').style.display='none';if(id==='saved')renderSaved();if(id==='progress')renderProgress();if(scroll)document.getElementById(id).scrollIntoView({behavior:'smooth',block:'start'});}
window.kitchenGo=go;
$$('#nav button').forEach(b=>b.onclick=()=>go(b.dataset.page));
$$('[data-kitchen-page]').forEach(a=>{const clone=a.cloneNode(true);a.replaceWith(clone);clone.addEventListener('click',e=>{e.preventDefault();go(clone.dataset.kitchenPage)})});
$$('[data-go]').forEach(a=>a.addEventListener('click',e=>{e.preventDefault();go(a.dataset.go)}));
$('#heroSearchButton').onclick=()=>{$('#search').focus()};
$('#heroSavedButton').onclick=()=>go('saved');$('#heroProgressButton').onclick=()=>go('progress');
$('.hero-find').onclick=()=>{resetRecipeFilters();go('recipes')};$('.hero-surprise').onclick=surprise;
function surprise(){const matches=recipes.filter(matchesRecipe),r=matches[Math.floor(Math.random()*matches.length)]||recipes[Math.floor(Math.random()*recipes.length)];resetRecipeFilters();go('recipes',{scroll:false});openRecipe(r.id)}
const previousSurprise=$('#surprise');const newSurprise=previousSurprise.cloneNode(true);previousSurprise.replaceWith(newSurprise);newSurprise.onclick=surprise;
const main=$('main');
for(const [id,title] of [['discover','Search the kitchen'],['saved','Your saved recipes'],['progress','Your cooking notebook']]){const section=document.createElement('section');section.id=id;section.className='page';section.innerHTML=`<h2>${title}</h2><div class="${id}-body"></div>`;main.insertBefore(section,$('.footer'));}
const nav=$('#nav');for(const [id,title] of [['saved','♡ Saved'],['progress','My notebook']]){const b=document.createElement('button');b.type='button';b.dataset.page=id;b.textContent=title;b.onclick=()=>go(id);nav.append(b)}
const original=$('#recipes>.grid');original.classList.add('original-grid');const records=document.createElement('details');records.className='original-records';records.innerHTML='<summary>Naomi’s original recipe records</summary><p>Your original ingredients and unfinished notes are kept here. The complete practice recipes above are separate additions.</p>';original.replaceWith(records);records.append(original);
$('#recipes>.sectionlead').textContent='Choose a recipe, adjust the quantities, then follow each step in cooking mode.';
const intro=document.createElement('div');intro.innerHTML=`<div class="collection-tools"><label>Find a recipe<input id="recipeQuery" type="search" placeholder="Try chicken, chocolate or quick…"></label><label>Category<select id="recipeCategory"><option value="">All recipes</option>${['Breakfast','Lunch','Dinner','Baking','Dessert','Drinks','Sauces'].map(c=>`<option>${c}</option>`).join('')}</select></label><label>Total time<select id="recipeTime"><option value="">Any time</option><option value="15">Up to 15 minutes</option><option value="30">Up to 30 minutes</option><option value="60">Up to 1 hour</option></select></label><button class="kbtn" id="resetRecipes">Reset</button></div><p id="recipeCount" role="status"></p><p class="recipe-legend">Times are estimates for the stated batch and include resting where listed. Follow the visual cues and doneness checks. These are authored practice recipes, not a claim of kitchen testing. Quantities scale; cooking times do not scale in direct proportion.</p><div id="readyRecipes" class="grid ready-grid"></div>`;
records.before(intro);
const allergy=document.createElement('p');allergy.className='source-note';allergy.textContent='Recipes are written without nuts, banana or plantain. Check ingredient labels and cross-contact warnings for your own allergies. Equipment and batch size affect timings.';records.before(allergy);
function total(r){return r.prep+r.cook+r.rest}
function matchesRecipe(r){const q=$('#recipeQuery')?.value.trim().toLowerCase()||'',cat=$('#recipeCategory')?.value||'',limit=Number($('#recipeTime')?.value)||Infinity;return (!cat||r.category===cat)&&total(r)<=limit&&(!q||[r.title,r.category,...r.ingredients.map(i=>i.name),...r.tags].join(' ').toLowerCase().includes(q))}
function equipment(r){return r.equipment||({Breakfast:'Mixing bowl, whisk, frying pan and spatula.',Lunch:'Chopping board, knife, saucepan or roasting tray as directed, and a spoon.',Dinner:'Chopping board, knife, pans or baking tray as directed; a clean food probe for meat or fish.',Baking:'Kitchen scales, mixing bowls, baking tin or tray, oven gloves and cooling rack.',Dessert:'Kitchen scales, mixing bowl and the pan or baking dish described below.',Drinks:'Measuring jug and a sieve or blender, as directed.',Sauces:'Heavy saucepan, whisk or spatula, measuring jug and heatproof bowl.'}[r.category])}
function storage(r){if(r.safety==='rice'||['mushroom-risotto'].includes(r.id))return 'Rice: cool quickly, ideally within 1 hour, refrigerate and use within 24 hours. Reheat once until steaming hot throughout.';if(['choc-cookies','brownies','vanilla-cupcakes','flatbreads','pizza-practice'].includes(r.id))return 'Cool baked goods before covering. Store unfilled cookies and cakes in an airtight container; freeze surplus. Refrigerate perishable toppings and cooked pizza promptly.';return 'For perishable leftovers, cool promptly and refrigerate within 1–2 hours. Use within 48 hours or freeze. Reheat only once until steaming hot throughout. Keep the fridge at 5°C or below.'}
function stepsHTML(r){return r.steps.map((s,i)=>`<li><strong>${esc(s.title)}</strong>${s.time?` <span class="step-time">About ${s.time} min</span>`:''}<p>${esc(s.text)}</p></li>`).join('')}
function recipeCard(r){const saved=state.saved.includes(r.id);return `<article class="card ready-card" data-recipe-id="${r.id}"><span class="recipe-category">${esc(r.category)}</span><h3>${esc(r.title)}</h3><div class="recipe-time"><b>About ${total(r)} min total</b><br>Prep ${r.prep} min · Cook ${r.cook} min${r.rest?` · Rest/cool ${r.rest} min`:''} · Makes ${r.serves} ${['choc-cookies','vanilla-cupcakes'].includes(r.id)?'pieces':'portions'}</div><div class="recipe-actions"><button class="kbtn primary" data-cook="${r.id}">Start cooking</button><button class="kbtn ${saved?'saved':''}" data-save="${r.id}" aria-pressed="${saved}">${saved?'♥ Saved':'♡ Save'}</button></div><details><summary>Ingredients, method & the science</summary><p><b>Equipment:</b> ${esc(equipment(r))}</p><label class="serving-control">${['choc-cookies','vanilla-cupcakes'].includes(r.id)?'Pieces':'Portions'} <input type="number" min="1" max="24" step="1" value="${r.serves}" data-portions="${r.id}" aria-label="Portions for ${esc(r.title)}"></label><ul class="ingredient-list">${r.ingredients.map((i,n)=>`<li><label><input type="checkbox" data-ingredient="${r.id}:${n}" ${state.checked[r.id+':'+n]?'checked':''}><span><b data-quantity="${i.q}" data-base="${r.serves}">${i.q}</b> ${esc(i.unit)} ${esc(i.name)}</span></label></li>`).join('')}</ul><p class="mini">Tick ingredients as you prepare them. Round fractional eggs by beating an egg and measuring the required share; use practical batch sizes.</p><h4>Method</h4><ol class="recipe-steps">${stepsHTML(r)}</ol><div class="science-box"><b>Why it works</b><br>${esc(r.science)}<br><button class="kbtn" data-lesson="${r.lesson}">Explore the science →</button></div><div class="rescue-box"><b>If it goes wrong</b><br>${esc(r.fix)}</div><div class="storage-box">${esc(storage(r))}</div><div class="recipe-actions"><button class="kbtn" data-print="${r.id}">Print recipe</button></div></details></article>`}
function bindCards(root){$$('[data-save]',root).forEach(b=>b.onclick=()=>{const id=b.dataset.save;state.saved=state.saved.includes(id)?state.saved.filter(x=>x!==id):[...state.saved,id];persist();$$(`[data-save="${id}"]`).forEach(x=>{const on=state.saved.includes(id);x.textContent=on?'♥ Saved':'♡ Save';x.classList.toggle('saved',on);x.setAttribute('aria-pressed',on)});if($('#saved').classList.contains('active'))renderSaved();toast(state.saved.includes(id)?'Saved to your recipes.':'Removed from saved recipes.')});$$('[data-cook]',root).forEach(b=>b.onclick=()=>startCooking(b.dataset.cook));$$('[data-lesson]',root).forEach(b=>b.onclick=()=>openLesson(b.dataset.lesson));$$('[data-portions]',root).forEach(input=>input.oninput=()=>{const r=recipes.find(x=>x.id===input.dataset.portions),n=Number(input.value);if(!Number.isInteger(n)||n<1||n>24){input.setCustomValidity('Choose a whole number from 1 to 24.');return}input.setCustomValidity('');$$('[data-quantity]',input.closest('.ready-card')).forEach(q=>q.textContent=Number((Number(q.dataset.quantity)*n/r.serves).toFixed(2)))});$$('[data-ingredient]',root).forEach(c=>c.onchange=()=>{state.checked[c.dataset.ingredient]=c.checked;persist()});$$('[data-print]',root).forEach(b=>b.onclick=()=>{const card=b.closest('.ready-card');card.classList.add('print-target');$('details',card).open=true;window.print();card.classList.remove('print-target')})}
function renderRecipes(){const found=recipes.filter(matchesRecipe);$('#recipeCount').textContent=`${found.length} of ${recipes.length} complete recipes`;$('#readyRecipes').innerHTML=found.length?found.map(recipeCard).join(''):'<p class="section-empty">No complete recipe matches those filters. Try another category or a longer time.</p>';bindCards($('#readyRecipes'))}
function resetRecipeFilters(){$('#recipeQuery').value='';$('#recipeCategory').value='';$('#recipeTime').value='';renderRecipes()}
['recipeQuery','recipeCategory','recipeTime'].forEach(id=>$('#'+id).addEventListener('input',renderRecipes));$('#resetRecipes').onclick=resetRecipeFilters;
function openRecipe(id){resetRecipeFilters();go('recipes',{scroll:false});const card=$('#readyRecipes [data-recipe-id="'+id+'"]');if(card){$('details',card).open=true;card.scrollIntoView({behavior:'smooth',block:'start'})}}
$$('.categoryRibbon button').forEach((b,i)=>b.onclick=()=>{const cats=['Breakfast','Lunch','Dinner','','Baking','Drinks','Sauces','Dessert','',''];resetRecipeFilters();$('#recipeCategory').value=cats[i];if(i===8){go('pairings');return}if(i===9){$('#recipeQuery').value='apple'}renderRecipes();go('recipes')});
function renderSaved(){const found=recipes.filter(r=>state.saved.includes(r.id));$('.saved-body').innerHTML=`<p class="sectionlead">Saved on this browser and device.</p><div class="grid ready-grid">${found.length?found.map(recipeCard).join(''):'<p class="section-empty">Tap ♡ Save on a recipe to build your collection.</p>'}</div>`;bindCards($('.saved-body'))}
const stats=document.createElement('div');stats.className='kitchen-stats';stats.innerHTML=`<span><b>${recipes.length}</b> complete recipes</span><span><b>${lessons.length}</b> science lessons</span><span>Step-by-step cooking mode</span>`;$('#home').prepend(stats);
function searchKitchen(){const q=$('#search').value.trim().toLowerCase();if(!q){go('home',{scroll:false});return}const rr=recipes.filter(r=>[r.title,r.category,...r.ingredients.map(i=>i.name),r.science].join(' ').toLowerCase().includes(q));const ll=lessons.filter(l=>[l.title,l.summary,l.why,l.fix].join(' ').toLowerCase().includes(q));$('.discover-body').innerHTML=`<p>${rr.length} recipe${rr.length===1?'':'s'} and ${ll.length} lesson${ll.length===1?'':'s'} for “${esc(q)}”</p><div class="grid">${ll.map(l=>`<article class="card"><span class="tag sage">Food science</span><h3>${esc(l.title)}</h3><p>${esc(l.summary)}</p><button class="kbtn" data-lesson="${l.id}">Open lesson →</button></article>`).join('')}</div><div class="grid ready-grid" style="margin-top:18px">${rr.map(recipeCard).join('')}</div>${!rr.length&&!ll.length?'<p class="section-empty">Try a dish, ingredient or technique, such as roux, chicken, caramel or starch.</p>':''}`;bindCards($('.discover-body'));go('discover',{scroll:false})}
let searchDebounce;$('#search').addEventListener('input',()=>{clearTimeout(searchDebounce);searchDebounce=setTimeout(searchKitchen,180)});$('#heroSearchForm').addEventListener('submit',e=>{e.preventDefault();clearTimeout(searchDebounce);searchKitchen();$('#discover').scrollIntoView({behavior:'smooth'})});
let activeLesson=lessons[0].id;
$('#science').innerHTML='<h2>Food Science, step by step</h2><p class="sectionlead">Choose a technique. Learn why it works, practise it, and recognise when it is ready.</p><div class="lesson-tabs" role="tablist" aria-label="Food science topics"></div><div id="lessonContent" role="tabpanel"></div>';
$('.lesson-tabs').innerHTML=lessons.map((l,i)=>`<button role="tab" id="lesson-tab-${l.id}" aria-controls="lessonContent" aria-selected="${i===0}" tabindex="${i===0?0:-1}" data-topic="${l.id}">${esc(l.title.split(':')[0])}</button>`).join('');
$$('[data-topic]').forEach((b,i,all)=>{b.onclick=()=>renderLesson(b.dataset.topic);b.onkeydown=e=>{if(['ArrowRight','ArrowLeft','Home','End'].includes(e.key)){e.preventDefault();const n=e.key==='Home'?0:e.key==='End'?all.length-1:(i+(e.key==='ArrowRight'?1:-1)+all.length)%all.length;all[n].focus();all[n].click()}}});
function openLesson(id){renderLesson(lessons.some(x=>x.id===id)?id:'browning');go('science')}
function renderLesson(id){activeLesson=id;const l=lessons.find(x=>x.id===id);$$('[data-topic]').forEach(b=>{const on=b.dataset.topic===id;b.setAttribute('aria-selected',on);b.tabIndex=on?0:-1});$('#lessonContent').setAttribute('aria-labelledby','lesson-tab-'+id);$('#lessonContent').innerHTML=`<div class="lesson-layout"><article class="lesson-main"><h3>${esc(l.title)}</h3><p>${esc(l.summary)}</p><div class="science-box"><b>What is happening?</b><p>${esc(l.why)}</p></div><h4>Set yourself up</h4><p>${esc(l.setup)}</p>${id==='roux'?rouxLab():id==='caramel'?caramelLab():''}<h4>Follow the process</h4><ol>${l.steps.map(s=>`<li><h4>${esc(s.title)} ${s.time?`<span class="step-time">About ${s.time} min</span>`:''}</h4><p>${esc(s.text)}</p></li>`).join('')}</ol><p class="recipe-legend">Timings are guides. Pan material, batch size, hob strength and ingredient temperature change the pace. Use the cues alongside the clock.</p></article><aside class="lesson-side"><h4>How do I know it is ready?</h4><p>${esc(l.signs)}</p><div class="rescue-box"><b>If it goes wrong</b><p>${esc(l.fix)}</p></div><button class="kbtn primary" data-practise="${l.recipe}">Practise with a recipe →</button><p class="lesson-source">Further reading: <a href="${l.source}" target="_blank" rel="noopener">food science reference ↗</a></p></aside></div>`;$('[data-practise]').onclick=()=>openRecipe(l.recipe);if(id==='roux')bindRoux();if(id==='caramel')bindCaramel()}
function rouxLab(){return `<div class="stage-lab"><h4>Choose your roux stage</h4><div class="stage-buttons">${[['White','#f6e4b8'],['Blond','#d2ab67'],['Brown','#ab7443']].map((x,i)=>`<button data-roux="${i}" aria-pressed="${i===0}" style="--stage:${x[1]}">${x[0]}</button>`).join('')}</div><p id="rouxStage" class="stage-note" aria-live="polite"></p><h4>White-sauce quantity helper</h4><div class="ratio-fields"><label>Milk (ml)<input id="rouxMilk" type="number" value="500" min="100" max="2000" step="50"></label><label>Consistency<select id="rouxThickness"><option value=".06">Light</option><option value=".08" selected>Medium</option><option value=".1">Thick</option></select></label></div><p id="rouxRatio" aria-live="polite"></p><p class="mini">A starting ratio for plain wheat-flour white sauce. Dark roux and gluten-free flours need different recipes.</p></div>`}
function bindRoux(){const notes=['White: about 2–3 minutes after flour is added. Keep ivory, gently bubbling and without browning. Good for béchamel.','Blond: often 5–8 minutes total. Look for a pale biscuit colour and lightly toasted aroma. Useful in stock-based sauces.','Brown: often 10–20 minutes or longer for a light brown stage. Look for even toasted colour; thickening is weaker. Stop if the fat or flour burns.'];$$('[data-roux]').forEach(b=>b.onclick=()=>{$$('[data-roux]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#rouxStage').textContent=notes[Number(b.dataset.roux)]});$('[data-roux]').click();const ratio=()=>{const n=Number($('#rouxMilk').value);$('#rouxRatio').textContent=n>=100&&n<=2000?`${Math.round(n*Number($('#rouxThickness').value))} g butter + ${Math.round(n*Number($('#rouxThickness').value))} g plain flour for ${n} ml milk.`:'Choose 100–2,000 ml milk.'};$('#rouxMilk').oninput=ratio;$('#rouxThickness').onchange=ratio;ratio()}
function caramelLab(){return '<div class="stage-lab"><h4>What colour is your sugar?</h4><div class="stage-buttons"><button data-caramel="0" style="--stage:#faf3de">Clear</button><button data-caramel="1" style="--stage:#ead29a">Straw</button><button data-caramel="2" style="--stage:#ce882c">Amber</button><button data-caramel="3" style="--stage:#7b431f;color:white">Very dark</button></div><p id="caramelStage" class="stage-note" aria-live="polite"></p><p class="mini">These colours are illustrations, not a calibrated doneness test. Use a light pan, aroma and the full recipe.</p></div>'}
function bindCaramel(){const notes=['Water is boiling away; no caramel colour yet. Stay nearby and avoid stirring after boiling begins.','Colour has started. Stay beside the pan: the next change can happen quickly.','The usual stopping point for the linked sauce. Remove from heat and finish carefully as instructed.','The risk of burning is high. If smoky, blackened or acrid, let it cool safely and remake. Do not taste hot sugar.'];$$('[data-caramel]').forEach(b=>b.onclick=()=>{$$('[data-caramel]').forEach(x=>x.setAttribute('aria-pressed',x===b));$('#caramelStage').textContent=notes[Number(b.dataset.caramel)]});$('[data-caramel]').click()}
const sauceIntro=document.createElement('div');sauceIntro.innerHTML='<p class="sectionlead">Cook the foundations with exact quantities, then explore what makes them work.</p><div class="recipe-actions"><button class="kbtn primary" id="openSauceRecipes">Open complete sauce recipes</button><button class="kbtn" id="openRouxLesson">Interactive roux lesson</button><button class="kbtn" id="openCaramelLesson">Caramel lesson</button></div>';$('#sauces>h2').after(sauceIntro);$('#openSauceRecipes').onclick=()=>{resetRecipeFilters();$('#recipeCategory').value='Sauces';renderRecipes();go('recipes')};$('#openRouxLesson').onclick=()=>openLesson('roux');$('#openCaramelLesson').onclick=()=>openLesson('caramel');
function renderProgress(){const entries=recipes.filter(r=>(state.progress[r.id]||[]).length);$('.progress-body').innerHTML=`<p>Check off steps in cooking mode. Notes and progress are saved on this browser and device${storageOK?'':'; persistent storage is currently unavailable'}.</p><ul class="progress-list">${entries.map(r=>`<li><span>${esc(r.title)}</span><button class="kbtn" data-cook="${r.id}">${state.progress[r.id].length}/${r.steps.length} steps · Resume</button></li>`).join('')||'<li>No recipes started yet. Choose “Start cooking” on a recipe.</li>'}</ul><h3>Your kitchen notes</h3><label for="kitchenNotes">What worked, what changed, and what to try next</label><textarea id="kitchenNotes" class="personal-notes" placeholder="My oven browned the cookies at 11 minutes…"></textarea><p class="mini" id="notesStatus" role="status"></p>`;$('#kitchenNotes').value=state.notes;$('#kitchenNotes').oninput=()=>{state.notes=$('#kitchenNotes').value;persist();$('#notesStatus').textContent=storageOK?'Saved on this device.':'Kept for this visit only.'};bindCards($('.progress-body'))}
const dialog=document.createElement('dialog');dialog.className='cook-dialog';dialog.setAttribute('aria-labelledby','cookTitle');dialog.innerHTML='<div class="dialog-head"><h2 id="cookTitle"></h2><button class="close-dialog" aria-label="Close cooking mode">×</button></div><progress class="cook-progress" max="100" value="0"></progress><div class="cook-step"></div><div class="timer-box"><b id="timerLabel">Kitchen timer</b><output id="timerDisplay" aria-live="off">00:00</output><div class="timer-actions"><label>Minutes <input id="timerMinutes" type="number" min="1" max="180" value="5"></label><button class="kbtn" id="timerStart">Start</button><button class="kbtn" id="timerPause">Pause</button><button class="kbtn" id="timerReset">Reset</button></div><p class="timer-note">Use this as a reminder, not a doneness test. Keep the page open; phone backgrounding can delay alerts. Hot sugar needs continuous attention.</p></div><div class="cook-nav"><button class="kbtn" id="cookPrev">← Previous</button><button class="kbtn primary" id="cookNext">Next step →</button></div>';
document.body.append(dialog);const dock=document.createElement('button');dock.className='timer-dock';dock.hidden=true;document.body.append(dock);
let cooking=null,stepIndex=0,timer={end:0,left:0,running:false,label:'Kitchen timer',recipe:null},alarmDone=false;
function startCooking(id){cooking=recipes.find(r=>r.id===id);const done=state.progress[id]||[];stepIndex=cooking.steps.findIndex((_,i)=>!done.includes(i));if(stepIndex<0)stepIndex=0;renderCook();if(!dialog.open)dialog.showModal()}
function renderCook(){const s=cooking.steps[stepIndex],done=state.progress[cooking.id]||[];$('#cookTitle').textContent=cooking.title;$('.cook-progress').value=done.length/cooking.steps.length*100;$('.cook-step').innerHTML=`<div class="step-count">Step ${stepIndex+1} of ${cooking.steps.length}</div><h3>${esc(s.title)}</h3><p>${esc(s.text)}</p><label class="cook-check"><input type="checkbox" id="stepDone" ${done.includes(stepIndex)?'checked':''}>I have completed this step</label>`;$('#stepDone').onchange=e=>{const d=new Set(state.progress[cooking.id]||[]);if(e.target.checked)d.add(stepIndex);else d.delete(stepIndex);state.progress[cooking.id]=[...d];persist();$('.cook-progress').value=d.size/cooking.steps.length*100};$('#cookPrev').disabled=stepIndex===0;$('#cookNext').textContent=stepIndex===cooking.steps.length-1?'Finish session':'Next step →';if(!timer.running&&!timer.left)$('#timerMinutes').value=Math.max(1,s.time||5);}
$('.close-dialog').onclick=()=>dialog.close();$('#cookPrev').onclick=()=>{if(stepIndex>0){stepIndex--;renderCook()}};$('#cookNext').onclick=()=>{if(stepIndex<cooking.steps.length-1){stepIndex++;renderCook()}else{dialog.close();toast('Session saved. Your checked steps are in My notebook.')}};
$('#timerStart').onclick=()=>{const min=Number($('#timerMinutes').value);if(!Number.isFinite(min)||min<1||min>180){toast('Choose a timer from 1 to 180 minutes.');return}if(timer.running){toast('Pause or reset the running timer before starting another.');return}const duration=timer.left||min*60000;timer={end:Date.now()+duration,left:duration,running:true,label:timer.left?timer.label:cooking.steps[stepIndex].title,recipe:timer.left?timer.recipe:cooking.id};alarmDone=false;updateTimer()};$('#timerPause').onclick=()=>{if(timer.running){timer.left=Math.max(0,timer.end-Date.now());timer.running=false;$('#timerStart').textContent='Resume';updateTimer()}};$('#timerReset').onclick=()=>{timer={end:0,left:0,running:false,label:'Kitchen timer',recipe:null};alarmDone=false;$('#timerStart').textContent='Start';updateTimer()};dock.onclick=()=>{if(timer.recipe)startCooking(timer.recipe);else if(cooking&&!dialog.open)dialog.showModal()};
function updateTimer(){if(timer.running)timer.left=Math.max(0,timer.end-Date.now());const seconds=Math.ceil(timer.left/1000),display=String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');$('#timerDisplay').textContent=display;$('#timerLabel').textContent=timer.label;dock.hidden=!timer.left&&!timer.running&&!alarmDone;dock.textContent=alarmDone?'Timer finished — check your food':`${timer.running?'⏱':'Paused'} ${display} · ${timer.label}`;if(timer.running&&timer.left===0){timer.running=false;alarmDone=true;toast('Timer finished. Check the recipe cues before moving on.');$('#timerStart').textContent='Start';try{navigator.vibrate?.([200,100,200])}catch(e){}}}
setInterval(updateTimer,500);
// Connect the original home filters to the complete recipe metadata.
window.updateCount=function(){const n=recipes.filter(homeMatch).length;$('#liveCount').textContent=`${n} matching complete recipe${n===1?'':'s'}`};
function homeMatch(r){const val=id=>$('#'+id).value.toLowerCase();return (!val('fTime')||total(r)<=Number(val('fTime')))&&(!val('fEase')||r.tags.some(x=>x.toLowerCase()===val('fEase')))&&(!val('fTemp')||r.tags.some(x=>x.toLowerCase()===val('fTemp')))&&(!val('fFlavor')||r.tags.some(x=>x.toLowerCase()===val('fFlavor')))&&(!val('fTexture')||r.tags.some(x=>x.toLowerCase()===val('fTexture')))&&(!val('fType')||r.category.toLowerCase()===val('fType')||(r.foodTypes||[]).some(x=>x.toLowerCase()===val('fType')))&&(!val('fCuisine')||r.tags.some(x=>x.toLowerCase()===val('fCuisine')))}
const oldMatch=$('#showMatches');const match=oldMatch.cloneNode(true);oldMatch.replaceWith(match);match.onclick=()=>{resetRecipeFilters();const found=recipes.filter(homeMatch);$('#readyRecipes').innerHTML=found.length?found.map(recipeCard).join(''):'<p class="section-empty">No complete recipe matches every selected choice. Broaden your choices and try again.</p>';$('#recipeCount').textContent=`${found.length} home-filter matches`;bindCards($('#readyRecipes'));go('recipes')};
['fTime','fEase','fTemp','fFlavor','fTexture','fType','fCuisine'].forEach(id=>$('#'+id).onchange=window.updateCount);
renderRecipes();renderLesson(activeLesson);window.updateCount();
const source=document.createElement('p');source.className='source-note';source.innerHTML='Cooking checks: <a href="https://www.food.gov.uk/safety-hygiene/cooking-your-food" target="_blank" rel="noopener">Food Standards Agency</a> · <a href="https://www.foodstandards.gov.scot/consumer-advice/food-safety/food-safety-in-the-kitchen/cooking" target="_blank" rel="noopener">cooling, leftovers and rice</a>. Science lessons include further-reading links.';$('#recipes').append(source);
})();
