(() => {
'use strict';
const $=(q,r=document)=>r.querySelector(q), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pretty=s=>s.replace(/-/g,' ').replace(/\b\w/g,c=>c.toUpperCase());
$('#showHotspots').onclick=e=>{const on=$('.hero').classList.toggle('reveal-spots');e.currentTarget.setAttribute('aria-pressed',on);e.currentTarget.textContent=on?'Hide labels':'Show me where ♡'};
$('#artDrinks').onclick=()=>{$('#recipeQuery').value='';$('#recipeTime').value='';$('#recipeCategory').value='Drinks';$('#recipeCategory').dispatchEvent(new Event('input'));window.kitchenGo('recipes')};
const section=document.createElement('section');section.id='reference';section.className='page';section.innerHTML=`<p class="eyebrow">THE BIGGER BOOKSHELF</p><h2>A world of food to explore</h2><p class="sectionlead">Search food composition and historic cookbooks. Every collection keeps its identity and source.</p><div class="reference-counts" id="referenceCounts" aria-live="polite">Loading collection counts…</div><div class="reference-switch" role="group" aria-label="Reference collection"><button class="kbtn primary" data-ref-mode="foods" aria-pressed="true">Food reference</button><button class="kbtn" data-ref-mode="archive" aria-pressed="false">Historical recipe archive</button></div><p id="referenceIntro"></p><form id="referenceForm" class="collection-tools"><label>Search this collection<input type="search" id="referenceQuery" placeholder="Try apples, raw or boiled…"></label><label id="refCategoryLabel">Food group<select id="referenceCategory"><option value="">All groups</option></select></label><button class="kbtn primary" type="submit">Search</button><button class="kbtn" type="button" id="referenceReset">Reset</button></form><label class="reference-check"><input type="checkbox" id="hideKnownAllergens" checked> Hide records mentioning nuts, banana or plantain</label><p class="source-note">This is a keyword filter, not an allergy safety check. Historical recipes and food records may omit ingredients or cross-contact information.</p><p id="referenceStatus" role="status"></p><div id="referenceResults" class="reference-grid"></div><div class="reference-paging"><button class="kbtn" id="referencePrev">← Previous</button><span id="referencePage"></span><button class="kbtn" id="referenceNext">Next →</button></div><details class="reference-coverage"><summary>What is included—and what still needs writing?</summary><p>The 6,000+ goal for each area is not complete. The modern collection currently has 28 authored practice recipes and 14 technique lessons. Archive recipes have not been converted into modern, tested tutorials. Food records include prepared foods and raw/cooked variants; they are not 7,793 distinct fruits or vegetables.</p><p>Historical methods may use obsolete measures, temperatures or preservation advice. They are presented for reference, with no invented cooking times or claim of current food-safety review.</p><p><a href="https://github.com/AdamBouhmad/open-recipe-archive" target="_blank" rel="noopener">Open Recipe Archive</a> · <a href="https://fdc.nal.usda.gov/download-datasets/" target="_blank" rel="noopener">USDA FoodData Central, SR Legacy (April 2018)</a> · <a href="./data/manifest.json">Exact collection counts & source versions</a></p></details>`;
$('main').insertBefore(section,$('.footer'));
const nav=document.createElement('button');nav.type='button';nav.dataset.page='reference';nav.textContent='Food & recipe archive';nav.onclick=()=>openReference('foods');$('#nav').append(nav);
for(const [id,mode,text] of [['ingredients','foods','Explore 7,793 food records →'],['pairings','archive','Browse 54,843 historical recipes →'],['recipes','archive','Explore the historical recipe archive →']]){const b=document.createElement('button');b.className='kbtn reference-entry';b.textContent=text;b.onclick=()=>openReference(mode);$('#'+id+' h2').after(b)}
const more=document.createElement('a');more.href='#reference';more.textContent='Food & recipe archive';more.onclick=e=>{e.preventDefault();openReference('archive')};$('.hero-more-menu').append(more);
let mode='foods',page=0,filtered=[],manifest=null,version=0;const cache={},pending={};
let bookmarks=[];try{bookmarks=JSON.parse(localStorage.getItem('little-miss-archive-bookmarks')||'[]');if(!Array.isArray(bookmarks))bookmarks=[]}catch(e){}
const knownAllergens=/\b(almonds?|nuts?|peanuts?|walnuts?|hazelnuts?|cashews?|pecans?|pistachios?|macadamias?|marzipan|praline|bananas?|plantains?)\b/i;
async function compressed(name){if(cache[name])return cache[name];if(pending[name])return pending[name];pending[name]=(async()=>{if(!window.DecompressionStream)throw new Error('Please use a current browser to open the compressed collections. Source links are available below.');const r=await fetch('./data/'+name+'.json.gz');if(!r.ok)throw new Error('The collection could not load. Please try again.');const data=await new Response(r.body.pipeThrough(new DecompressionStream('gzip'))).json();cache[name]=data;return data})();try{return await pending[name]}finally{delete pending[name]}}
async function getManifest(){if(manifest)return manifest;const r=await fetch('./data/manifest.json');if(!r.ok)throw new Error('Collection counts are unavailable.');manifest=await r.json();$('#referenceCounts').innerHTML=`<div><b>${manifest.foodRecords.toLocaleString()}</b><span>food reference records</span></div><div><b>${manifest.archiveRecords.toLocaleString()}</b><span>historical recipe records</span></div><div><b>${window.KITCHEN_RECIPES.length}</b><span>modern practice recipes</span></div><div><b>${window.KITCHEN_LESSONS.length}</b><span>detailed technique lessons</span></div>`;return manifest}
async function openReference(next){mode=next;page=0;$('#referenceQuery').value='';$('#referenceCategory').value='';window.kitchenGo('reference');await load()}
async function load(){const current=++version;$('#referenceStatus').textContent='Opening the collection…';$('#referenceResults').innerHTML='';$('#referencePrev').disabled=true;$('#referenceNext').disabled=true;$('#referencePage').textContent='';document.querySelectorAll('[data-ref-mode]').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.refMode===mode);b.classList.toggle('primary',b.dataset.refMode===mode)});$('#referenceIntro').textContent=mode==='foods'?'USDA SR Legacy food composition. Values are per 100 g of the named food, in the preparation state shown. These are reference measurements, not personalised nutrition advice.':'Explore public-domain cookbook records from 31 collections. Historical source text is preserved; quantities, timing and suitability may be incomplete. Use the modern recipe collection for guided cooking.';$('#referenceQuery').placeholder=mode==='foods'?'Try apples, raw or boiled…':'Search recipe titles, e.g. soup or pancakes…';try{const m=await getManifest();if(current!==version)return;const cat=$('#referenceCategory'),selected=cat.value,groups=mode==='foods'?m.foodCategories:m.collections;cat.innerHTML='<option value="">All '+(mode==='foods'?'food groups':'collections')+'</option>'+Object.keys(groups).sort().map(g=>`<option value="${esc(g)}">${esc(mode==='foods'?g:pretty(g))} (${groups[g].toLocaleString()})</option>`).join('');cat.value=selected in groups?selected:'';await compressed(mode==='foods'?'foods':'archive-index');if(current===version)filter()}catch(e){if(current!==version)return;$('#referenceStatus').textContent=e.message;const retry=document.createElement('button');retry.className='kbtn';retry.textContent='Try loading again';retry.onclick=load;$('#referenceResults').append(retry)}}
function filter(){const records=cache[mode==='foods'?'foods':'archive-index'];if(!records)return;const words=$('#referenceQuery').value.toLowerCase().trim().split(/\s+/).filter(Boolean),group=$('#referenceCategory').value,hide=$('#hideKnownAllergens').checked;filtered=records.filter(r=>{const title=mode==='foods'?r.title:r[2],category=mode==='foods'?r.category:r[3],hay=(title+' '+category+(mode==='archive'?' '+r[4]:'')).toLowerCase(),allergen=mode==='foods'?knownAllergens.test(title):r[6];return (!group||group===category)&&(!hide||!allergen)&&words.every(w=>hay.split(/[^\p{L}\p{N}]+/u).some(token=>token.startsWith(w)))});page=0;render()}
function render(){const start=page*18,end=Math.min(start+18,filtered.length);$('#referenceStatus').textContent=`${filtered.length.toLocaleString()} matching ${mode==='foods'?'food':'historical recipe'} records${$('#hideKnownAllergens').checked?' · keyword exclusions on':''}`;$('#referencePage').textContent=filtered.length?`${start+1}–${end} of ${filtered.length.toLocaleString()}`:'No matches';$('#referencePrev').disabled=page===0;$('#referenceNext').disabled=end>=filtered.length;$('#referenceResults').innerHTML=filtered.length?filtered.slice(start,end).map((r,j)=>`<article class="reference-card"><p class="eyebrow">${esc(mode==='foods'?r.category:pretty(r[3]))}</p><h3>${esc(mode==='foods'?r.title:r[2])}</h3><p class="source-note">${mode==='foods'?'USDA · SR Legacy · per 100 g':'Historical source · '+esc(r[5]||'date unspecified')}</p><button class="kbtn" data-reference-open="${start+j}">${mode==='foods'?'See food composition':'Read historical recipe'} →</button></article>`).join(''):'<p class="section-empty">No matching records. Try fewer words, another group, or reset the search.</p>';document.querySelectorAll('[data-reference-open]').forEach(b=>b.onclick=()=>showRecord(filtered[+b.dataset.referenceOpen]));}
$('#referenceForm').onsubmit=e=>{e.preventDefault();filter()};$('#referenceCategory').onchange=filter;$('#hideKnownAllergens').onchange=filter;$('#referenceReset').onclick=()=>{$('#referenceQuery').value='';$('#referenceCategory').value='';$('#hideKnownAllergens').checked=true;filter()};let queryTimer;$('#referenceQuery').oninput=()=>{clearTimeout(queryTimer);queryTimer=setTimeout(filter,180)};$('#referencePrev').onclick=()=>{page--;render();$('#referenceForm').scrollIntoView({behavior:'smooth'})};$('#referenceNext').onclick=()=>{page++;render();$('#referenceForm').scrollIntoView({behavior:'smooth'})};document.querySelectorAll('[data-ref-mode]').forEach(b=>b.onclick=()=>openReference(b.dataset.refMode));
const dialog=document.createElement('dialog');dialog.className='cook-dialog reference-dialog';dialog.setAttribute('aria-labelledby','referenceTitle');dialog.innerHTML='<div class="dialog-head"><h2 id="referenceTitle"></h2><button class="close-dialog" aria-label="Close reference">×</button></div><div id="referenceDetail"></div>';document.body.append(dialog);$('.close-dialog',dialog).onclick=()=>dialog.close();let recordVersion=0;dialog.addEventListener('close',()=>recordVersion++);
function safeUrl(s){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'#'}catch(e){return '#'}}
function sourceBody(body){return body.split('\n').map(line=>{if(/^##\s/.test(line))return `<h3>${esc(line.replace(/^##\s*/,''))}</h3>`;if(!line.trim())return '';return `<p class="archive-line">${esc(line)}</p>`}).join('')}
async function showRecord(r){const current=++recordVersion;$('#referenceTitle').textContent=mode==='foods'?r.title:r[2];$('#referenceDetail').textContent='Loading source record…';dialog.showModal();dialog.scrollTop=0;if(mode==='foods'){$('#referenceDetail').innerHTML=`<p>${esc(r.category)} · USDA SR Legacy</p><p>Per <b>100 g</b> of this exact food and preparation state. Missing values are not assumed to be zero.</p><table class="nutrition-table"><thead><tr><th scope="col">Nutrient</th><th scope="col">Per 100 g</th></tr></thead><tbody>${Object.entries(r.nutrients).map(([name,value])=>`<tr><th scope="row">${esc(name)}</th><td>${esc(value)}</td></tr>`).join('')}</tbody></table><p class="source-note">April 2018 reference dataset. Foods with similar names can have different composition. This record is not a recipe or a full ingredient/allergen declaration.</p><a class="kbtn" href="https://fdc.nal.usda.gov/food-details/${encodeURIComponent(r.id)}/nutrients" target="_blank" rel="noopener">View original USDA record ↗</a>`;return}try{const records=await compressed('archive-'+r[0]);if(current!==recordVersion||!dialog.open)return;const source=records[r[1]],key=r[0]+':'+r[1];$('#referenceDetail').innerHTML=`<div class="archive-notice"><b>Historical reference • not a modern cooking tutorial</b><p>This source has not been checked for current food safety or your allergies. Historical preservation methods, ingredient treatments and doneness advice may be unsafe today. Missing quantities and timings have not been invented.</p></div><p class="source-note">${esc(source.author)} · <i>${esc(source.source_title)}</i> · ${esc(source.source_year)}<br>Source licence: ${esc(source.license)}. Imported through Open Recipe Archive; transcription and translation may contain errors.</p><div class="recipe-actions"><button class="kbtn" id="bookmarkArchive">${bookmarks.includes(key)?'♥ Bookmarked':'♡ Bookmark reference'}</button><a class="kbtn" href="${esc(safeUrl(source.source_url))}" target="_blank" rel="noopener">Original source ↗</a></div><div class="archive-body">${sourceBody(source.body)}</div><p class="source-note">Explore the modern technique lessons for current explanations of browning, roux, caramel and more.</p>`;$('#bookmarkArchive').onclick=e=>{bookmarks=bookmarks.includes(key)?bookmarks.filter(x=>x!==key):[...bookmarks,key];try{localStorage.setItem('little-miss-archive-bookmarks',JSON.stringify(bookmarks));e.currentTarget.textContent=bookmarks.includes(key)?'♥ Bookmarked':'♡ Bookmark reference'}catch(err){e.currentTarget.textContent='Could not save in this browser'}}}catch(e){$('#referenceDetail').textContent=e.message}}
// Archive bookmarks are deliberately separate from the modern cooking collection.
const savedButton=document.createElement('button');savedButton.className='kbtn';savedButton.textContent='My bookmarked historical references';savedButton.onclick=async()=>{mode='archive';await openReference('archive');if(!cache['archive-index'])return;filtered=cache['archive-index'].filter(r=>bookmarks.includes(r[0]+':'+r[1]));page=0;render();$('#referenceStatus').textContent=filtered.length+' bookmarked historical references (all bookmarks shown)'};$('.reference-switch').append(savedButton);
const homeEntry=document.createElement('div');homeEntry.className='reference-home';homeEntry.innerHTML='<b>The bigger bookshelf</b><p>7,793 food records · 54,843 historical recipe records</p><button class="kbtn" id="homeFoodReference">Explore food reference</button> <button class="kbtn" id="homeRecipeArchive">Explore historical recipes</button>';$('#home .kitchen-stats').after(homeEntry);$('#homeFoodReference').onclick=()=>openReference('foods');$('#homeRecipeArchive').onclick=()=>openReference('archive');
$('#heroSearchForm').addEventListener('submit',()=>{const q=$('#search').value.trim();let extra=$('#searchReferenceLinks');if(!extra){extra=document.createElement('div');extra.id='searchReferenceLinks';extra.className='reference-home';$('.discover-body').append(extra)}extra.innerHTML='<p>Search the larger reference collections for <b>'+esc(q||'all records')+'</b></p><button class="kbtn" data-search-reference="foods">Search food reference</button> <button class="kbtn" data-search-reference="archive">Search historical recipe titles</button>';extra.querySelectorAll('[data-search-reference]').forEach(b=>b.onclick=async()=>{await openReference(b.dataset.searchReference);$('#referenceQuery').value=q;filter()})});
getManifest().catch(()=>{$('#referenceCounts').textContent='Collection counts will load when you open this section.'});
})();
